---
abstract: 'Dispatch::Profile Moose constructor coderef store'
author:
  - 'James Spurin <james@spurin.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dispatch-Profile-CodeStore
requires:
  Moose: '0'
  Moose::Util::TypeConstraints: '0'
  strict: '0'
version: '0.001'
